// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zummzziydfpvwuxxuyyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1bW16eml5ZGZwdnd1eHh1eXl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTkxNzksImV4cCI6MjA2NDA3NTE3OX0.AFoGIoREPaRBX1Lvo1-c7ctiJiyknvY-YKWTldMJDzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);