-- Create the thesis_data table
CREATE TABLE thesis_data (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode varchar NOT NULL UNIQUE,
    thesis_title text NOT NULL,
    authors text[] NOT NULL,
    department varchar NOT NULL,
    publication_year integer NOT NULL,
    upload_date timestamptz NOT NULL DEFAULT now(),
    last_modified timestamptz NOT NULL DEFAULT now(),
    is_deleted boolean NOT NULL DEFAULT false,
    
    -- Add constraints
    CONSTRAINT valid_publication_year CHECK (publication_year >= 1900 AND publication_year <= extract(year from now())),
    CONSTRAINT valid_barcode CHECK (barcode ~ '^[A-Za-z0-9-]+$')
);

-- Create indexes for frequently searched columns
CREATE INDEX idx_thesis_data_barcode ON thesis_data (barcode);
CREATE INDEX idx_thesis_data_title ON thesis_data USING gin (to_tsvector('english', thesis_title));
CREATE INDEX idx_thesis_data_department ON thesis_data (department);
CREATE INDEX idx_thesis_data_publication_year ON thesis_data (publication_year);

-- Create a trigger to update last_modified timestamp
CREATE OR REPLACE FUNCTION update_last_modified()
RETURNS TRIGGER AS $$
BEGIN
    NEW.last_modified = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_thesis_data_last_modified
    BEFORE UPDATE ON thesis_data
    FOR EACH ROW
    EXECUTE FUNCTION update_last_modified();

-- Enable Row Level Security
ALTER TABLE thesis_data ENABLE ROW LEVEL SECURITY;

-- Create policies for different operations
-- Allow anyone to view non-deleted thesis records
CREATE POLICY "View thesis records" ON thesis_data
    FOR SELECT
    USING (NOT is_deleted);

-- Only authenticated users can insert new records
CREATE POLICY "Insert thesis records" ON thesis_data
    FOR INSERT
    TO authenticated
    WITH CHECK (true);

-- Only authenticated users can update their records
CREATE POLICY "Update thesis records" ON thesis_data
    FOR UPDATE
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Soft delete policy - only authenticated users can mark records as deleted
CREATE POLICY "Soft delete thesis records" ON thesis_data
    FOR UPDATE
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Create types for the thesis_data table
CREATE TYPE public.thesis_status AS ENUM ('draft', 'published', 'archived');

-- Add comments for documentation
COMMENT ON TABLE thesis_data IS 'Stores thesis records with metadata';
COMMENT ON COLUMN thesis_data.barcode IS 'Unique identifier for each thesis';
COMMENT ON COLUMN thesis_data.thesis_title IS 'Complete title of the thesis';
COMMENT ON COLUMN thesis_data.authors IS 'Array of author names';
COMMENT ON COLUMN thesis_data.department IS 'Academic department';
COMMENT ON COLUMN thesis_data.publication_year IS 'Year thesis was published';
COMMENT ON COLUMN thesis_data.is_deleted IS 'Soft delete flag';